CREATE TABLE Owner(
OwnerID INT (3) PRIMARY KEY NOT NULL,
OwnerName VARCHAR(50) NOT NULL,
TelNo INT(11) NOT NULL,
Email VARCHAR(30) NOT NULL
);

CREATE TABLE Dog(
DogID VARCHAR (4) PRIMARY KEY NOT NULL,
OwnerID INT (3) NOT NULL,
DogName VARCHAR(20) NOT NULL,
Breed VARCHAR(30) NOT NULL,
Size VARCHAR(6) NOT NULL,
Coat VARCHAR(6) NOT NULL,
Comments VARCHAR(35),
FOREIGN KEY (OwnerID) REFERENCES Owner(OwnerID)
);

CREATE TABLE Grooming(
GroomType VARCHAR (4) PRIMARY KEY NOT NULL,
Description VARCHAR(30) NOT NULL,
GroomTime INT (2) NOT NULL,
GroomCost REAL NOT NULL
);

CREATE TABLE Appointment(
DogID VARCHAR (4) NOT NULL,
GroomType VARCHAR (4) NOT NULL,
BookingDate DATE NOT NULL,
BookingTime TIME NOT NULL,
PRIMARY KEY (DogID, GroomType, BookingDate,BookingTime),
FOREIGN KEY(DogID) REFERENCES Dog(DogID),
FOREIGN KEY(GroomType) REFERENCES Grooming(GroomType)
);
